embedding_dim: 256
num_encoder_layers: 5
num_attn_heads: 8
normalization: batch
optimizer: Adam
learning_rate: 0.0001
weight_decay: 1.0e-06
pomo_num_starts: !!python/tuple
- 400
val_num_samples: 10000
train_decode_type: sampling
temperature: 1.0
max_epochs: 300
num_loc_train: 100
batch_size: 64
train_data_size: 100000
limit_train_batches: 0.5
check_val_every_n_epoch: 1
checkpoint_after_epoch: 0
loc_sampler: <rl4co.envs.common.distribution_utils.Mix_Multi_Distributions object
  at 0x749fc90123e0>
min_demand: 3
max_demand: 30
val_batch_size: 1
dataloader_num_workers: 4
val_data_size: 0
log_base_dir: lightning_logs/small_exp1
num_val_instances: 16
val_instances:
- X-n110-k13
- X-n115-k10
- X-n153-k22
- X-n172-k51
- X-n120-k6
- X-n129-k18
- X-n125-k30
- X-n134-k13
- X-n344-k43
- X-n351-k40
- X-n393-k38
- X-n420-k130
- X-n376-k94
- X-n384-k52
- X-n317-k53
- X-n367-k17
