embedding_dim: 256
num_encoder_layers: 5
num_attn_heads: 8
normalization: instance
optimizer: Adam
learning_rate: 0.0001
weight_decay: 1.0e-06
train_num_starts: null
val_num_samples: 10000
val_temperature: 1.0
lr_reduce_factor: 0.7
lr_reduce_patience: 3
lr_reduce_threshold: 0.001
train_decode_type: sampling
train_temperature: 1.0
max_epochs: 5
num_loc_train: 100
batch_size: 64
train_data_size: 50000
test_data_size: 100
test_seed: 1234
train_seed: 800179731
train_set_clusters: 4
limit_train_batches: null
check_val_every_n_epoch: 1
checkpoint_after_epoch: 0
min_demand: 3
max_demand: 30
vehicle_capacity: 120.0
val_batch_size: 1
dataloader_num_workers: 4
val_data_size: 0
log_base_dir: lightning_logs/small_exp2
num_test_instances: 16
test_instances:
- X-n110-k13
- X-n115-k10
- X-n153-k22
- X-n172-k51
- X-n120-k6
- X-n129-k18
- X-n125-k30
- X-n134-k13
- X-n344-k43
- X-n351-k40
- X-n393-k38
- X-n420-k130
- X-n376-k94
- X-n384-k52
- X-n317-k53
- X-n367-k17
